#!/bin/bash
set -e

set_ownership() {
    chown -R ubsmd:ubsmd /usr/bin/ubsmd /usr/lib/ubs_mem \
        /usr/lib/aarch64-linux-gnu/libubsm_sdk.so /etc/ubs_mem \
        /usr/include/ubs_mem 2>/dev/null || true
}

create_log_directory() {
    mkdir -p /var/log/ubsm/
    chown -R ubsmd:ubsmd /var/log/ubsm 2>/dev/null || true
}

case "$1" in
    configure)
        set_ownership
        create_log_directory
        ;;
esac

#DEBHELPER#
